/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_ncepu_abe_CP_ABE */

#ifndef _Included_edu_ncepu_abe_CP_ABE
#define _Included_edu_ncepu_abe_CP_ABE
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_ncepu_abe_CP_ABE
 * Method:    setup
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_edu_ncepu_abe_CP_1ABE_setup(JNIEnv *env,
		jclass jclass);

/*
 * Class:     edu_ncepu_abe_CP_ABE
 * Method:    encrypt
 * Signature: (Ljava/nio/ByteBuffer;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_edu_ncepu_abe_CP_1ABE_encrypt(JNIEnv *env,
		jclass jcla, jbyteArray pk, jstring policy, jstring key);

/*
 * Class:     edu_ncepu_abe_CP_ABE
 * Method:    kengen
 * Signature: ([B[B[Ljava/lang/String;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject  JNICALL Java_edu_ncepu_abe_CP_1ABE_kengen(JNIEnv *env,
		jclass jcla, jbyteArray pk, jbyteArray mk, jobjectArray attrs);
/*
 * Class:     edu_ncepu_abe_CP_ABE
 * Method:    decrypt
 * Signature: ([B[B[B)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jstring JNICALL Java_edu_ncepu_abe_CP_1ABE_decrypt(JNIEnv *env,
		jclass jcla, jbyteArray pk, jbyteArray jba_prv, jbyteArray jba_cph);
#ifdef __cplusplus
}
#endif
#endif
